version: "3.7"
services:
  webserver:
    image: nginx
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    ports:
      - 8080:80
    networks:
      internal:
        aliases:
          - ser

  webclient:
    image: alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    depends_on:
      - webserver
    networks:
      internal:
        aliases:
          - cli
    command: ping ser

networks:
  internal: